name: BurgerTransfer
on: 
  workflow_dispatch:
    inputs:
      FROM:
        description: 'FROM: Integer'
        required: true
        default: '0'
      TO:
        description: 'TO: Integer'
        required: true
        default: '0'
      AMOUNT:
        description: 'AMOUNT: Integer'
        required: true
        default: '0'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run Claimer
      run: echo ${{ secrets.CONFIG_MAINNET }} | dotnet run --project BurgerTransfer
      env:
        WIF: ${{ secrets.TEEWIF }}
        RPC: https://n3seed1.ngd.network:10332
        FROM: ${{ github.event.inputs.FROM }}
        TO: ${{ github.event.inputs.TO }}
        AMOUNT: ${{ github.event.inputs.AMOUNT }}
