name: BurgerClaimer
on: 
  workflow_dispatch:
  
  schedule:
  - cron: "0 0,6,12,18 * * *"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run Claimer
      run: echo ${{ secrets.CONFIG_MAINNET }} | dotnet run --project BurgerClaimer
      env:
        WIF: ${{ secrets.TEEWIF }}
        RPC: https://n3seed2.ngd.network:10332
        THREASHOLD: 4294967296
