name: BurgerClaimer
on: 
  workflow_dispatch:
  
  schedule:
  - cron: "0 0,6,12,18 * * *"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run Claimer
      run: echo ${{ secrets.CONFIG_MAINNET }} | dotnet run --project BurgerClaimer
      env:
        WIF: ${{ secrets.TEEWIF }}
        RPC: https://n3seed2.ngd.network:10332
        THREASHOLD: 17179869184
    - name: action-keepalive-check
      run: |
        if (( $(git --no-pager log -1 --format=%ct) < $(date --date "last month" +%s) )); then
          git config --global user.email bot@neoburger.io
          git config --global user.name bot
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/neoburger/TEE.git
          git commit --allow-empty -m "Dummy commit created to keep the repository active..."
          git push origin HEAD
        fi