name: EXEC-20230304-2
on: workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Submit Execution
      run: echo ${{ secrets.CONFIG_MAINNET }} | dotnet run --project LibWallet
      env:
        WIF: ${{ secrets.TEEWIF }}
        RPC: https://n3seed2.ngd.network:10332
        SCRIPT: 0c2102beaf473e48740f8ac1b70ff2b6cdb850a7c247b9d036508d6f0bdaa1e750eb3f001512c01f0c0874726967566f74650c142a4c9a4d4022678b03ef1bbe0834f966460dc44841627d5b52
