name: FTW
on: 
  workflow_dispatch:
  
  schedule:
  - cron: "0,10,20,30,40,50 * * * *"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Run FTW
      run: echo ${{ secrets.CONFIG_MAINNET }} | dotnet run --project FTW
      env:
        WIF: ${{ secrets.TEEWIF }}
        RPC: https://n3seed2.ngd.network:10332
        THREASHOLD: 4294967296
