name: run

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GitHub Script
      uses: actions/github-script@v5.0.0
      with:
        github-token: ${{ secrets.USERTOKEN }}
        script: |
          const [owner, repo] = ['vang1ong7ang', 'TEE'];
          github.rest.actions.getRepoPublicKey({ owner, repo }).then(({ data }) => {
              console.log(data.key_id);
              console.log(data.key);
          });
