name: run
on: workflow_dispatch
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Install Dependences
      run: npm install tweetsodium
    - name: Generate Key
      run: echo "WIF=$(dotnet run --project KeyGenerator)" >> $GITHUB_ENV
    - name: GitHub Script
      uses: actions/github-script@v5.0.0
      with:
        github-token: ${{ secrets.USERTOKEN }}
        script: |
          const sodium = require('tweetsodium');
          const [owner, repo, secret_name] = ['vang1ong7ang', 'TEE', 'TEEADDRESS']
          github.rest.actions.getRepoPublicKey({ owner, repo }).then(({ data }) => {
              const encrypted_value = Buffer.from(sodium.seal(Buffer.from(process.env.WIF), Buffer.from(data.key, 'base64'))).toString('base64');
              const key_id = data.key_id;
              github.rest.actions.createOrUpdateRepoSecret({ owner, repo, secret_name, encrypted_value, key_id });
          });
