name: run

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependences
      run: npm install tweetsodium
    - name: GitHub Script
      uses: actions/github-script@v5.0.0
      with:
        github-token: ${{ secrets.USERTOKEN }}
        script: |
          const sodium = require('tweetsodium');
          const [owner, repo, secret_name] = ['vang1ong7ang', 'TEE', 'TEEADDRESS']
          github.rest.actions.getRepoPublicKey({ owner, repo }).then(({ data }) => {
              const messageBytes = Buffer.from('plain-text');
              const keyBytes = Buffer.from(data.key, 'base64');
              const encrypted_value = Buffer.from(sodium.seal(messageBytes, keyBytes)).toString('base64');
              const key_id = data.key_id;
              console.log(data.key_id);
              console.log(data.key);
              console.log(encrypted);
              github.rest.actions.createOrUpdateRepoSecret({ owner, repo, secret_name, encrypted_value, key_id });
          });
