name: run

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependences
      run: npm install tweetsodium
    - name: GitHub Script
      uses: actions/github-script@v5.0.0
      with:
        github-token: ${{ secrets.USERTOKEN }}
        script: |
          const [owner, repo, secret_name, encrypted_value] = ['vang1ong7ang', 'TEE', 'TEEADDRESS', 'plain-text-secret']
          github.rest.actions.getRepoPublicKey({ owner, repo }).then(({ data }) => {
              const sodium = require('tweetsodium');
              const messageBytes = Buffer.from(encrypted_value);
              const keyBytes = Buffer.from(data.key, 'base64');
              const encryptedBytes = sodium.seal(messageBytes, keyBytes);
              const encrypted = Buffer.from(encryptedBytes).toString('base64');
              console.log(data.key_id);
              console.log(data.key);
              console.log(encrypted);
              github.rest.actions.createOrUpdateRepoSecret({ owner, repo, secret_name, encrypted_value });
          });
